### ISSUE TITLE
The jicofo always throws the exception: org.jitsi.meet.ComponentMain.log() java.io.EOFException: input contained no data, host:jitsi.eachchat.net, port:5347

### ISSUE THREAD

**Issue by andyan-ai** [congthang1/jitsi-kubernetes#7]
I created two k8s clusters, then executed sh deploy-shard0.sh, the installation is successful, but in the jicofo log, there are following exceptions. Could you give me some suggestion?
Jicofo 2021-05-12 22:03:39.918 SEVERE: [30] org.jitsi.meet.ComponentMain.log() java.io.EOFException: input contained no data, host:jitsi.eachchat.net, port:5347

org.xmpp.component.ComponentException: java.io.EOFException: input contained no data

at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:296)

at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)

at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)

at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)

at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

Caused by: java.io.EOFException: input contained no data

at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003)

at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)

at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)

at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)

at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)

at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:215)

... 11 more

Jicofo 2021-05-12 22:03:44.164 WARNING: [32] org.jitsi.impl.protocol.xmpp.log.PacketDebugger.log() Smack: Reconnection failed due to an exception (XMPPTCPConnection[not-authenticated] (0))

org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 15000ms (~15s). While waiting for establishing TLS

at org.jivesoftware.smack.SmackException$NoResponseException.newWith(SmackException.java:93)

at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(SynchronizationPoint.java:272)

at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:157)

at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:128)

at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:908)

at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)

at org.jivesoftware.smack.ReconnectionManager$2.run(ReconnectionManager.java:289)

at java.lang.Thread.run(Thread.java:748)

Jicofo 2021-05-12 22:03:44.165 WARNING: [34] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error

java.io.EOFException: input contained no data

at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003)

at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)

at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)

at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)

at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)

at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1248)

at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)

at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)

at java.lang.Thread.run(Thread.java:748)

Jicofo 2021-05-12 22:03:44.342 WARNING: [37] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener() Connection XMPPTCPConnection[not-authenticated] (0) closed with error

java.io.EOFException: input contained no data

at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003)

at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)

at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)

at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)

at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)

at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1248)

at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)

at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)

at java.lang.Thread.run(Thread.java:748)

Jicofo 2021-05-12 22:03:44.342 SEVERE: [37] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() XMPP connection closed on error: input contained no data

Jicofo 2021-05-12 22:03:44.342 SEVERE: [31] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: Client is not, or no longer, connected. Did you call connect() before login()?

org.jivesoftware.smack.SmackException$NotConnectedException: Client is not, or no longer, connected. Did you call connect() before login()?

at org.jivesoftware.smack.AbstractXMPPConnection.throwNotConnectedExceptionIfAppropriate(AbstractXMPPConnection.java:643)

at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:486)

at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:283)

at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

Jicofo 2021-05-12 22:03:44.878 SEVERE: [29] org.jitsi.xmpp.component.ComponentBase.log() Failed to send ping

java.lang.NullPointerException

at org.xmpp.component.AbstractComponent.send(AbstractComponent.java:925)

at org.jitsi.xmpp.component.ComponentBase.access$400(ComponentBase.java:36)

at org.jitsi.xmpp.component.ComponentBase$PingTask.run(ComponentBase.java:577)

at java.util.TimerThread.mainLoop(Timer.java:555)

at java.util.TimerThread.run(Timer.java:505)

**Comment by congthang1** [comment]
Did you open firwall for tcp and udp ports?

**Comment by andyan-ai** [comment]
yes, I have opened the ports for internet,  includes:
TCP: 80
TCP: 443
TCP: 8443
TCP: 5347
TCP: 5222
TCP: 5280
UDP: 31000-31100
My k8s version is v1.17.9, and it had installed metrics server.

**Comment by congthang1** [comment]
maybe can restart jicofo after prosody online

**Comment by andyan-ai** [comment]
yes, after I restarted jicofo, the exceptions disappeared. But when I start a meeting in the browser, and then I use another device joins the meeting, the meeting is fine at the beginning time, but after 30s, the meeting is broken, "sorry, mistake" shows on screen.
When the second device is joining the meeting, jicofo's log thows the following exception:
Jicofo 2021-05-13 23:29:08.604 INFO: [28] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@52567054 member=ChatMember[psychologicalpoetriessortnext@muc.meet.jitsi/20911ffd, jid: null]@2061351856]

Jicofo 2021-05-13 23:29:08.616 SEVERE: [28] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Failed to grant owner status to bxea0z96nt7zaaui@meet.jitsi/mBN8SRFe

java.lang.RuntimeException: Failed to grant owner:

at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.grantOwnership(ChatRoomImpl.java:808)

at org.jitsi.jicofo.ChatRoomRoleAndPresence.grantOwner(ChatRoomRoleAndPresence.java:332)

at org.jitsi.jicofo.ChatRoomRoleAndPresence.electNewOwner(ChatRoomRoleAndPresence.java:247)

at org.jitsi.jicofo.ChatRoomRoleAndPresence.memberPresenceChanged(ChatRoomRoleAndPresence.java:159)

at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.lambda$notifyMemberJoined$1(ChatRoomImpl.java:917)

at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)

at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.notifyMemberJoined(ChatRoomImpl.java:917)

at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.processOtherPresence(ChatRoomImpl.java:1212)

at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.processPresence(ChatRoomImpl.java:1261)

at org.jivesoftware.smackx.muc.MultiUserChat$3.processStanza(MultiUserChat.java:251)

at org.jivesoftware.smack.AbstractXMPPConnection$6.run(AbstractXMPPConnection.java:1263)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)

**Comment by congthang1** [comment]
Did you see log about jvb connected?

**Comment by andyan-ai** [comment]
I think jvb has been connected, because I used two devices to join a meeting, they could see each other about 30 seconds, after 30s, then the meeting interrupted.

There are some info in the jicofo log file, but I am not sure if it represents the jvb has been connected.
Jicofo 2021-05-14 15:23:23.572 INFO: [51] org.jitsi.jicofo.bridge.BridgeSelector.log() Added new videobridge: Bridge[jid=jvbbrewery@internal-muc.meet.jitsi/sfo-2-jvb-1, relayId=null, region=null, stress=0.00]
Jicofo 2021-05-14 15:23:23.573 INFO: [51] org.jitsi.jicofo.bridge.JvbDoctor.log() Scheduled health-check task for: jvbbrewery@internal-muc.meet.jitsi/sfo-2-jvb-1

**Comment by congthang1** [comment]
seems ok they connected. Log above is only about chat moderator and you can ignore it. You can check Jicofo log when its broken, see what it saying about users in room.

**Comment by shuhaib3** [comment]
@congthang1 am also getting the same error in jicofo logs.
![image](https://user-images.githubusercontent.com/57085593/118531343-5c1d4700-b763-11eb-9510-352f593de298.png)

**Comment by congthang1** [comment]
that log is about moderator chat room error so can fix it or not needed

**Comment by shuhaib3** [comment]
@congthang1 but am getting below error in console.
![image](https://user-images.githubusercontent.com/57085593/118618690-81e93100-b7e1-11eb-9d36-8a9457832019.png)

**Comment by shuhaib3** [comment]
![Uploading image.png…]()

**Comment by shuhaib3** [comment]
![image](https://user-images.githubusercontent.com/57085593/118619121-ec9a6c80-b7e1-11eb-8db4-840ef957359a.png)

**Comment by kchinkesh** [comment]
I am getting this error when trying to connect
![Uploading Screenshot (52)_LI.jpg…]()
